site_name: Neovim Plugin Template
site_description: A template for creating Neovim plugins with best practices and standardized structure
site_url: https://greggh.github.io/neovim-plugin-template/

repo_name: greggh/neovim-plugin-template
repo_url: https://github.com/greggh/neovim-plugin-template

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: INSTALLATION.md
  - Features: FEATURES.md
  - Development: DEVELOPMENT.md
  - Contributing: CONTRIBUTING.md
