name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    name: Lint and Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"
      
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4
      
      - name: Install Dependencies
        run: |
          luarocks install luacheck
          luarocks install stylua
      
      - name: Lint with Luacheck
        run: luacheck lua plugin
      
      - name: Check style with StyLua
        run: stylua --check lua plugin

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ['stable', 'nightly']
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}
      
      - name: Run Tests
        run: |
          cd tests
          nvim --headless -u tests/minimal_init.lua -c "lua require('plenary.busted').run()" || exit 1
  
  docs:
    name: Check Documentation
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      
      - name: Check Documentation
        run: |
          # Use vimdoc to check for documentation errors
          # Replace with actual doc check command if needed
          test -d doc || echo "No doc directory found"
